title: Welcome to Makayla's GitHub Pages!
description: This is a  webesite for the repository Makayla-A.github.io, created October 15, 2024, for CRCP 3320, Postmodern Software Design. It
was created by Makayla Alston and is maintained by GitHub.
theme: jekyll-theme-architect
